### ISSUE TITLE
"Error: Unexpected end" when chunked req packets are not complete XML string

### ISSUE THREAD

**Issue by hellosmithy** [rafaeljesus/koa-xml#1]
The code at https://github.com/rafaeljesus/koa-xml/blob/master/lib/xml.js#L11 is unable to parse the data unless it is a single packet. E.g. if the first chunk is `'<ro'` it is not yet valid XML and throws because it is being passed straight to `xml2js`.

**Comment by hellosmithy** [comment]
I've made a PR to fix this issue

**Comment by rafaeljesus** [comment]
Good job @hellosmithy
